### ISSUE TITLE
Reason to use odhcpd over dnsmasq

### ISSUE THREAD

**Issue by CReimer** [lede-project/source#219]
My current setup is an o2 Box 6431 as my main router
It's still OpenWRT 15.05.1 but since odhcpd is still in this repository I'm quite sure it's still used as before.

odhcpd seems to be used as a dedicated DHCPv6 service and dnsmasq serves only as DHCPv4 (and DNS cache of course).
Is this still from before version 2.60 of dnsmasq where IPv6 was unsupported? Couldn't dnsmasq replace odhcpd at this time?

**Comment by diizzyy** [comment]
It could, however someone needs to do the work and it's not been high priority as odhcpd still works.

**Comment by dedeckeh** [comment]
The feature set of odhcpd is inferior to the feature set of dnsmasq; at least for dhcpv4; but odhcpd is better integrated in the the OpenWRT/Lede architecture in terms of ubus, uci support.
Reloading config and interfaces getting active requires restart of dnsmasq while odhcpd has runtime support not requiring a restart. On top of that the code quality of dnsmasq is not that great.
The IPv6 feature set (DHCPv6, RA) is quite ok in odhcpd; I would be more in favour to extend the DHCPv4 feature set in odhcpd so we can get rid of dnsmasq (or limit its functionality to dns proxy)  due to the above mentioned reasons.

**Comment by ignisf** [comment]
>  On top of that the code quality of dnsmasq is not that great.

Quite mildly put :)

**Comment by KanjiMonster** [comment]
On top of that odhcpd has some features that dnsmasq lacks, e.g. DHCP reconfigure support (at least for v6), so renumeration with odhcp6c behind odhcpd should be near instantly (or with any other v6 client that supports it).

Since this is not really a bug and more a generic question/discussion, I'll close this ticket. For further discussion I recommend either the mailing list or IRC.
